name: Build thx

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15.6
      - name: Build thx binary
        run: |
          go build -o thx main.go
